name: packages
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  json_annotation: ^4.9.0
  powersync: ^1.11.2
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  supabase_flutter: ^2.8.3
  uuid: ^4.5.1
  connectivity_plus: ^6.1.3

  

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
